EG_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from account.views import Login, Register, OtpVerifyView

urlpatterns = [
    path('', include('portal.urls')),
    path('', include('products.urls')),
    path('', include('order.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('otp-verify/', OtpVerifyView.as_view(), name="otp-verify"),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import ProductList, ProductCreate, CategoryCreate, CategoryList, ProductUpdate, ProductDelete, \
    CategoryDelete, ProfileView, CollectionList, CollectionCreate, CollectionDelete

app_name = 'account'

urlpatterns = [
    path('', ProductList.as_view(), name='dashboard'),
    path('product/create', ProductCreate.as_view(), name='product_create'),
    path('product/update/<int:pk>', ProductUpdate.as_view(), name='product_update'),
    path('product/delete/<int:pk>', ProductDelete.as_view(), name='product_delete'),
    path('category/', CategoryList.as_view(), name='category'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/delete/<int:pk>', CategoryDelete.as_view(), name='category_delete'),
    path('collection/', CollectionList.as_view(), name='collection'),
    path('collection/create', CollectionCreate.as_view(), name='collection_create'),
    path('collection/delete/<int:pk>', CollectionDelete.as_view(), name='collection_delete'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from .views import add_user_order, user_open_order, remove_item_order, export_excel, generate_pdf,remove_all_order

app_name = 'order'
urlpatterns = [
    path('order', add_user_order, name='new-order'),
    path('open-order', user_open_order, name='open-order'),
    path('remove-order/<detail_id>', remove_item_order, name='remove-order'),
    path('remove-all-order/', remove_all_order, name='remove-all-order'),
    path('export_excel', export_excel, name='export-excel'),
    path('export_pdf', generate_pdf, name='export-pdf'),
]

portal/urls.py
from django.urls import path
from .views import HomeView, CategoryList, CollectionList

app_name = 'portal'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug:slug>', CategoryList.as_view(), name='category'),
    path('collection/<slug:slug>', CollectionList.as_view(), name='collection'),
]

products/urls.py
from django.urls import path
from .views import ProductList, product_detail_view, ProductPreview, SearchList

app_name = 'product'
urlpatterns = [
    path('product/', ProductList.as_view(), name='product_list'),
    path('product/<productId>/<slug:slug>', product_detail_view, name='product_detail'),
    path('preview/<int:pk>', ProductPreview.as_view(), name='product_preview'),
    path('search', SearchList.as_view(), name='search'),
    path('search/page/<int:page>', SearchList.as_view(), name='search'),
]

templates/base/shared/header.html
{% load static %}
<header id="header"><!--header-->
    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4" style="text-align: left;">
                    <div class="logo">
                        <a href="{% url 'portal:home' %}"><img src="{% static 'images/main/eg-logo.png' %}" alt="Logo"
                                                               style="text-align: center;"/></a>
                    </div>
                </div>

                <div class="col-sm-8 header-middle-menu">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'account:profile' %}"><i class="fa fa-user"></i> حساب کاربـری</a></li>
                            <li><a href="{% url 'order:open-order' %}"><i class="fa fa-shopping-cart"></i> سبد خریـد</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->
    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <form class="ml-3" action="{% url 'product:search' %}">
                        <div class="search_box pull-right" style="display: flex">
                            <input class="form-control form-control-navbar" type="text" name="q" placeholder="جستجو"
                                   aria-label="جستجو">
                            <div >
                                <button class="mr-1" type="submit" style="margin-right: 10px">
                                    <p>جستجو</p>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-right">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="{% url 'portal:home' %}" class="active">خـانه</a></li>
                            <li><a href="{% url 'product:product_list' %}">محصولات</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->