EG_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from account.views import Login, Register, OtpVerifyView

urlpatterns = [
    path('', include('portal.urls')),
    path('', include('products.urls')),
    path('', include('order.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('otp-verify/', OtpVerifyView.as_view(), name="otp-verify"),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import ProductList, ProductCreate, CategoryCreate, CategoryList, ProductUpdate, ProductDelete, \
    CategoryDelete, ProfileView, CollectionList, CollectionCreate, CollectionDelete

app_name = 'account'

urlpatterns = [
    path('', ProductList.as_view(), name='dashboard'),
    path('product/create', ProductCreate.as_view(), name='product_create'),
    path('product/update/<int:pk>', ProductUpdate.as_view(), name='product_update'),
    path('product/delete/<int:pk>', ProductDelete.as_view(), name='product_delete'),
    path('category/', CategoryList.as_view(), name='category'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/delete/<int:pk>', CategoryDelete.as_view(), name='category_delete'),
    path('collection/', CollectionList.as_view(), name='collection'),
    path('collection/create', CollectionCreate.as_view(), name='collection_create'),
    path('collection/delete/<int:pk>', CollectionDelete.as_view(), name='collection_delete'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from .views import add_user_order, user_open_order, remove_item_order, export_excel, generate_pdf,remove_all_order

app_name = 'order'
urlpatterns = [
    path('order', add_user_order, name='new-order'),
    path('open-order', user_open_order, name='open-order'),
    path('remove-order/<detail_id>', remove_item_order, name='remove-order'),
    path('remove-all-order/', remove_all_order, name='remove-all-order'),
    path('export_excel', export_excel, name='export-excel'),
    path('export_pdf', generate_pdf, name='export-pdf'),
]

products/urls.py
from django.urls import path
from .views import ProductList, product_detail_view, ProductPreview, SearchList

app_name = 'product'
urlpatterns = [
    path('product/', ProductList.as_view(), name='product_list'),
    path('product/<productId>/<slug:slug>', product_detail_view, name='product_detail'),
    path('preview/<int:pk>', ProductPreview.as_view(), name='product_preview'),
    path('search', SearchList.as_view(), name='search'),
    path('search/page/<int:page>', SearchList.as_view(), name='search'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True, verbose_name='ایمیل')
    phone = models.CharField(unique=True,max_length=15, verbose_name='شماره همراه', null=True)
    is_author = models.BooleanField(default=False, verbose_name='وضعیت نویسنده')


 

account/forms.py
from .models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class ProfileForms(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super(ProfileForms, self).__init__(*args, **kwargs)

        self.fields['username'].help_text = None

        if not user.is_superuser:
            self.fields['username'].disabled = True
            self.fields['email'].disabled = True
            self.fields['phone'].disabled = True
            self.fields['is_author'].disabled = True

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'is_author']


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ('username', 'email', 'phone', 'password1', 'password2')
        
        
class OtpForm(forms.Form):
    otp_code = forms.CharField(max_length=4)

account/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from products.models import Product, Category, Collection
from .forms import ProfileForms
from .mixins import FieldsMixin, FormValidMixin, AuthorAccessMixin, SuperUserAccessMixin, AuthorsAccessMixin
from .models import User
from django.contrib.auth.views import LoginView, PasswordChangeView


class ProductList(AuthorsAccessMixin, ListView):
    template_name = 'dashboard.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Product.objects.all()
        else:
            return Product.objects.filter(author=self.request.user)


class ProductCreate(AuthorsAccessMixin, FormValidMixin, FieldsMixin, CreateView):
    model = Product
    template_name = 'registration/product-create-update.html'


class ProductUpdate(AuthorAccessMixin, FormValidMixin, FieldsMixin, UpdateView):
    model = Product
    template_name = 'registration/product-create-update.html'


class ProductDelete(AuthorAccessMixin, SuperUserAccessMixin, FormValidMixin, FieldsMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('account:dashboard')
    template_name = 'registration/product_confirm_delete.html'


class CategoryList(LoginRequiredMixin, ListView):
    template_name = 'registration/category-list.html'
    queryset = Category.objects.all()


class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['title', 'slug', 'status', 'image']
    template_name = 'registration/category-create.html'


class CategoryDelete(AuthorAccessMixin, SuperUserAccessMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('account:category')
    template_name = 'registration/product_confirm_delete.html'


class CollectionList(LoginRequiredMixin, ListView):
    template_name = 'registration/collection-list.html'
    queryset = Collection.objects.all()


class CollectionCreate(LoginRequiredMixin, CreateView):
    model = Collection
    fields = ['title', 'slug']
    template_name = 'registration/collection-create.html'


class CollectionDelete(AuthorAccessMixin, SuperUserAccessMixin, FormValidMixin, FieldsMixin, DeleteView):
    model = Collection
    success_url = reverse_lazy('account:collection')
    template_name = 'registration/product_confirm_delete.html'


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'registration/profile.html'
    success_url = reverse_lazy('account:profile')
    form_class = ProfileForms

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)

    def get_form_kwargs(self):
        kwargs = super(ProfileView, self).get_form_kwargs()
        kwargs.update({
            'user': self.request.user
        })
        return kwargs


class Login(LoginView):
    def get_success_url(self):
        user = self.request.user

        if user.is_superuser or user.is_author:
            return reverse_lazy("account:dashboard")
        else:
            return reverse_lazy("account:profile")



import random
import threading
import time
from django.shortcuts import redirect
from django.views.generic import FormView
from django.contrib.auth import login
from .forms import SignupForm, OtpForm
from django.contrib import messages
from melipayamak import Api
from decouple import config



class OTPService:
    def __init__(self):
        self.username = config('USERNAME_PANEL')
        self.password = config('PASSWORD_PANEL')
        self._from = config('FROM_PANEL')
        self.api = Api(self.username, self.password)
        
    def generate_code(self):
        return random.randint(1000, 9999)
    
    def send_otp(self, phone_number, code):
        sms = self.api.sms()
        text = f"OTP Code: {code}"
        response = sms.send(to=phone_number, _from=self._from, text=text)
        print(response)
        return response
    

    
class Register(CreateView):
    form_class = SignupForm
    template_name = 'registration/register.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.otp_service = OTPService()

    def delete_code(self):
        time.sleep(10)
        self.request.session.pop('code', None)
        self.request.session.save()

    def form_valid(self, form):
        self.request.session['user_data'] = form.cleaned_data
        self.request.session.save()

        code = self.otp_service.generate_code()
        self.request.session['code'] = code

        to = str(self.request.session['user_data']['phone'])
        

        self.otp_service.send_otp(phone_number=to, code=code)


        tr1 = threading.Thread(target=self.delete_code)
        tr1.start()

        return redirect("otp-verify")



class OtpVerifyView(FormView):
    template_name = "registration/otp.html"
    form_class = OtpForm
    success_url = reverse_lazy("account:dashboard")
    
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Initialize OTPService
        self.otp_service = OTPService()

    def form_valid(self, form):
        code = self.request.POST['otp_code']
        
        if self.request.session.get('code') and int(code) == self.request.session['code']:
            # Process the user data as before
            user_data = self.request.session.get('user_data')
            if user_data:
                password = user_data.pop('password1')
                user_data.pop('password2', None)
                
                user = User(**user_data)
                user.is_author = True
                user.set_password(password)
                user.save()
                
                login(self.request, user)
                
                self.request.session.pop('user_data', None)
                self.request.session.pop('code', None)

            return redirect(self.success_url)
        else:
            messages.error(self.request, "The OTP code is incorrect. Please try again.")
            return redirect("otp-verify")

    def post(self, request, *args, **kwargs):
        if "resend_otp" in request.POST:
            # Resend OTP logic
            code = random.randint(1000, 10000)
            request.session['code'] = code
            
            # Generate and store OTP code in session
            code = self.otp_service.generate_code()
            self.request.session['code'] = code

            # Get the phone number from session user data
            to = str(self.request.session['user_data']['phone'])
            
            # Send OTP
            self.otp_service.send_otp(phone_number=to, code=code)

            messages.success(request, "A new OTP code has been sent.")
            return self.get(request, *args, **kwargs)  # Reload the page

        return super().post(request, *args, **kwargs)

account/templates/dashboard.html
{% extends 'registration/base.html' %}
{% load thumbnail %}
{% block title_meta %}{% block title %}لیست محصولات{% endblock %}{% endblock %}
{% block main %}
    <div class="row">
        <div class="col-12">
            {% if object_list %}
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th class="table-header">عنوان</th>
                                <th class="table-header">طراح</th>
                                <th class="table-header">تعداد قطعات</th>
                                <th class="table-header">تصویر محصول</th>
                                <th class="table-header">تاریخ انتشار</th>
                                <th class="table-header">دسته بندی</th>
                                <th class="table-header">کالکشن(شناسه)</th>
                                <th class="table-header">توضیحات</th>
                                <th class="table-header">وضعیت</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for obj in object_list %}
                                <tr>
                                    <td>{{ obj.title }}</td>
                                    <td>{{ obj.author.get_full_name }}</td>
                                    <td>{{ obj.parts }}</td>
                                    <td>
                                        {% thumbnail obj.image "110x110" crop="center" as im %}
                                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                        {% endthumbnail %}
                                    </td>
                                    <td>{{ obj.j_publish }}</td>
                                    <td>{{ obj.category_to_str }}</td>
                                    <td>{{ obj.collection_to_str }}</td>
                                    <td>{{ obj.description|striptags|truncatewords:10 }}</td>
                                    <td><span class="tag tag-success">
                                    {% if obj.status == 'p' %}
                                        <span class="right badge badge-success ">منتشر شده</span>
                                        <ul class="list-group">
                                            <li class="list-inline"><a class="btn btn-info mb-1" target="_blank"
                                                                       href="{% url 'product:product_detail' obj.id obj.slug %}">نمایش محصول</a></li>
                                            <li class="list-inline"><a class="btn btn-warning mb-1"
                                                                       href="{% url 'account:product_update' obj.pk %}">ویرایش محصول</a></li>
                                            {% if user.is_superuser %}
                                                <li class="list-inline"><a class="btn btn-danger mb-1"
                                                                           href="{% url 'account:product_delete' obj.pk %}">حذف محصول</a></li>
                                            {% endif %}
                                        </ul>
                                    {% else %}
                                        <span class="right badge badge-danger">پیش نویس</span>
                                        <ul class="list-group">
                                        <li class="list-inline"><a class="btn btn-secondary mb-1" target="_blank"
                                                                   href="{% url 'product:product_preview' obj.pk %}">پیش‌نمایش محصول</a></li>
                                        <li class="list-inline"><a class="btn btn-warning mb-1" target="_blank"
                                                                   href="{% url 'account:product_update' obj.pk %}">ویرایش محصول</a></li>
                                        </ul>
                                        {% if user.is_superuser %}
                                            <li class="list-inline"><a class="btn btn-danger mb-1"
                                                                       href="{% url 'account:product_delete' obj.pk %}">حذف محصول</a></li>
                                        {% endif %}
                                    {% endif %}
                                </span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            {% else %}
                <h3 class="text-info">محتوایی برای نمایش وجود ندارد!!!</h3>
            {% endif %}
            <!-- /.card -->
        </div>
    </div>
{% endblock %}