EG_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from account.views import Login, Register, OtpVerifyView

urlpatterns = [
    path('', include('portal.urls')),
    path('', include('products.urls')),
    path('', include('order.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('otp-verify/', OtpVerifyView.as_view(), name="otp-verify"),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import add_user_order, user_open_order, remove_item_order, export_excel, generate_pdf,remove_all_order

app_name = 'order'
urlpatterns = [
    path('order', add_user_order, name='new-order'),
    path('open-order', user_open_order, name='open-order'),
    path('remove-order/<detail_id>', remove_item_order, name='remove-order'),
    path('remove-all-order/', remove_all_order, name='remove-all-order'),
    path('export_excel', export_excel, name='export-excel'),
    path('export_pdf', generate_pdf, name='export-pdf'),
]

portal/urls.py
from django.urls import path
from .views import HomeView, CategoryList, CollectionList

app_name = 'portal'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug:slug>', CategoryList.as_view(), name='category'),
    path('collection/<slug:slug>', CollectionList.as_view(), name='collection'),
]

order/models.py
from django.db import models
from account.models import User
from products.models import Product


class Order(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    is_paid = models.BooleanField(verbose_name='پرداخت شده / نشده')
    order_date = models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت')

    class Meta():
        verbose_name = 'سفارش ثبت شده'
        verbose_name_plural = 'سفارش های ثبت شده'

    def __str__(self):
        return self.owner.get_full_name()


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='سبد خرید')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
    # price = models.IntegerField(verbose_name='قیمت محصول')
    count = models.IntegerField(verbose_name='تعداد')

    class Meta:
        verbose_name = 'جزییات محصول'
        verbose_name_plural = 'جزییات محصولات'

    def __str__(self):
        return self.product.title

order/forms.py
from django import forms


class UserOrderForm(forms.Form):
    product_id = forms.IntegerField(widget=forms.HiddenInput())
    count = forms.IntegerField(widget=forms.HiddenInput(), initial=1)

order/views.py
import datetime
import xlwt
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.template.loader import get_template
from xhtml2pdf import pisa
from products.models import Product
from .forms import UserOrderForm
from .models import Order, OrderDetail
from django.http import HttpResponse, FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter


@login_required
def add_user_order(request):
    new_order_form = UserOrderForm(request.POST or None)

    if new_order_form.is_valid():
        order = Order.objects.filter(owner_id=request.user.id, is_paid=False).first()
        if order is None:
            order = Order.objects.create(owner_id=request.user.id, is_paid=False)

        product_id = new_order_form.cleaned_data.get('product_id')
        count = new_order_form.cleaned_data.get('count')
        if count < 0:
            count = 1
        product = Product.objects.get_by_id(product_id=product_id)
        order.orderdetail_set.create(product_id=product_id, count=count)
        return redirect(f'/product/{product.id}/{product.slug}')

    return redirect('/')


@login_required
def user_open_order(request):
    context = {
        'order': None,
        'details': None,
    }
    open_order = Order.objects.filter(owner_id=request.user.id).first()
    if open_order is not None:
        context['order'] = open_order
        context['details'] = open_order.orderdetail_set.all()
    return render(request, 'order/user_open_order.html', context)


@login_required
def remove_item_order(request, *args, **kwargs):
    detail_id = kwargs.get('detail_id')
    if detail_id is not None:
        order_detail = OrderDetail.objects.get_queryset().get(id=detail_id, order__owner_id=request.user.id)
        if order_detail is not None:
            order_detail.delete()
        return redirect('order:open-order')


@login_required
def remove_all_order(request, *args, **kwargs):
    order_detail = OrderDetail.objects.all()
    if order_detail is not None:
        order_detail.delete()
    return redirect('order:open-order')


def export_excel(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=OrderDetail' + str(datetime.datetime.now()) + '.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('OrderDetail', cell_overwrite_ok=True)
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['image', 'slug', 'parts', 'technique']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)
    font_style = xlwt.XFStyle()
    rows = OrderDetail.objects.filter(order__owner=request.user).values_list('product__image', 'product__slug',
                                                                             'product__parts', 'product__image')
    for row in rows:
        row_num += 1

        for col_num in range(len(row)):
            ws.write(row_num, col_num, str(row[col_num]), font_style)

    wb.save(response)
    return response


def generate_pdf(request):
    open_order = Order.objects.filter(owner_id=request.user.id).first()
    context = {'order': open_order,
               'details': open_order.orderdetail_set.all(),
               }
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="orders.pdf"'

    # find the template and render it.
    template = get_template('order/pdf1.html')
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html.encode('utf-8'), dest=response, encodings='utf-8')

    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

order/templates/order/pdf1.html
<!DOCTYPE html>
{% load thumbnail %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of orders</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 2cm;
        }
    </style>
</head>
<body>
<section>
    <div>
        <div>
            <table>
                <thead>
                <tr style="border-bottom: 5px solid grey; margin-left: 10px">
                    <td style="color: darkblue"><strong>Image</strong></td>
                    <td style="color: darkblue"><strong>Collection ID</strong></td>
                    <td style="color: darkblue"><strong>Product ID</strong></td>
                    <td style="color: darkblue"><strong>Parts</strong></td>
                    <td style="color: darkblue"><strong>Color</strong></td>
                    <td style="color: darkblue"><strong>Technique</strong></td>
                    <td style="color: darkblue"><strong>Count</strong></td>
                </tr>
                </thead>
                <tbody>
                {% for detail in details %}
                    <tr style="border-bottom: 1px solid black; margin-left: 10px">
                        <td>
                            <img width="100" height="100" src="{{ detail.product.image.path }}"
                                 alt="">
                        </td>
                        <td style="border-right: 1px solid black">
                            <p>{{ detail.product.collection_to_str }}</p>
                        </td>
                        <td style="border-right: 1px solid black">
                            <p>{{ detail.product.slug }}</p>
                        </td>
                        <td style="border-right: 1px solid black">
                            <p>{{ detail.product.parts }}</p>
                        </td>
                        {% if detail.product.color %}
                            <td style="border-right: 1px solid black">
                                <p>{{ detail.product.color }}</p>
                            </td>
                        {% else %}
                            <td style="border-right: 1px solid black">
                                <p>-</p>
                            </td>
                        {% endif %}
                        {% if detail.product.technique %}
                            <td style="border-right: 1px solid black">
                                <p>{{ detail.product.technique }}</p>
                            </td>
                        {% else %}
                            <td style="border-right: 1px solid black">
                                <p>-</p>
                            </td>
                        {% endif %}
                        <td style="border-right: 1px solid black">
                            <p></p>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
<section>
    <div>
        <div>
            <div>
                <div>
                    <ul style="margin-top: 20px;">
                        <li><strong>Count of items: {{ details.count }}</strong></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>

order/templates/order/user_open_order.html
{% extends 'base/base.html' %}
{% load thumbnail %}
{% block content %}
    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="{% url 'portal:home' %}">خانـه</a></li>
                    <li class="active">لیست سفارشات</li>
                </ol>
            </div><!--/breadcrums-->
            {% if order != None and details|length > 0 %}
                <div class="table-responsive cart_info">
                    <table class="table table-condensed">
                        <thead>
                        <tr class="cart_menu">
                            <td class="image">تصویر</td>
                            <td class="description">شناسه کالکشن</td>
                            <td class="description">شناسه محصول</td>
                            <td class="price">تعداد قطعات</td>
                            <td class="quantity">رنگ</td>
                            <td class="total">تکنیک</td>
                            <td class="total">تعداد</td>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for detail in details %}
                            <tr>
                                <td class="cart_product">
                                    <a href="">
                                        {% thumbnail detail.product.image "110x110" crop="center" as im %}
                                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                        {% endthumbnail %}
                                    </a>
                                </td>
                                <td class="cart_description">
                                    <p>{{ detail.product.collection_to_str }}</p>
                                </td>
                                <td class="cart_description">
                                    <p>شناسـه : {{ detail.product.slug }}</p>
                                </td>
                                <td class="cart_price">
                                    <p>{{ detail.product.parts }}</p>
                                </td>
                                <td class="cart_quantity">
                                    <p>{{ detail.product.color }}</p>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price">{{ detail.product.technique }}</p>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price"></p>
                                </td>
                                <td class="cart_delete">
                                    <a class="cart_quantity_delete" href="{% url 'order:remove-order' detail.id %}"><i
                                            class="fa fa-times"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="alert alert-warning">
                    <p>هیچ محصولی انتخاب نشده است</p>
                </div>
            {% endif %}
        </div>
    </section>
    <section id="do_action">
        <div class="container">

            <div class="row">
                <div class="col-sm-6">
                    <div class="total_area">
                        <ul>
                            <li>تعداد آیتم ها <span>{{ details.count }}</span></li>
                        </ul>
                        {#                        <a class="btn btn-default update" href="{% url 'order:export-excel' %}">خروجی اکسل</a>#}
                        <a class="btn btn-default update" href="{% url 'order:remove-all-order' %}">پاکسازی لیست</a>
                        <a class="btn btn-default update" href="{% url 'order:export-pdf' %}">خروجی pdf</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}