EG_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from account.views import Login, Register, OtpVerifyView

urlpatterns = [
    path('', include('portal.urls')),
    path('', include('products.urls')),
    path('', include('order.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('otp-verify/', OtpVerifyView.as_view(), name="otp-verify"),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import ProductList, ProductCreate, CategoryCreate, CategoryList, ProductUpdate, ProductDelete, \
    CategoryDelete, ProfileView, CollectionList, CollectionCreate, CollectionDelete

app_name = 'account'

urlpatterns = [
    path('', ProductList.as_view(), name='dashboard'),
    path('product/create', ProductCreate.as_view(), name='product_create'),
    path('product/update/<int:pk>', ProductUpdate.as_view(), name='product_update'),
    path('product/delete/<int:pk>', ProductDelete.as_view(), name='product_delete'),
    path('category/', CategoryList.as_view(), name='category'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/delete/<int:pk>', CategoryDelete.as_view(), name='category_delete'),
    path('collection/', CollectionList.as_view(), name='collection'),
    path('collection/create', CollectionCreate.as_view(), name='collection_create'),
    path('collection/delete/<int:pk>', CollectionDelete.as_view(), name='collection_delete'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from .views import add_user_order, user_open_order, remove_item_order, export_excel, generate_pdf,remove_all_order

app_name = 'order'
urlpatterns = [
    path('order', add_user_order, name='new-order'),
    path('open-order', user_open_order, name='open-order'),
    path('remove-order/<detail_id>', remove_item_order, name='remove-order'),
    path('remove-all-order/', remove_all_order, name='remove-all-order'),
    path('export_excel', export_excel, name='export-excel'),
    path('export_pdf', generate_pdf, name='export-pdf'),
]

portal/urls.py
from django.urls import path
from .views import HomeView, CategoryList, CollectionList

app_name = 'portal'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug:slug>', CategoryList.as_view(), name='category'),
    path('collection/<slug:slug>', CollectionList.as_view(), name='collection'),
]

products/urls.py
from django.urls import path
from .views import ProductList, product_detail_view, ProductPreview, SearchList

app_name = 'product'
urlpatterns = [
    path('product/', ProductList.as_view(), name='product_list'),
    path('product/<productId>/<slug:slug>', product_detail_view, name='product_detail'),
    path('preview/<int:pk>', ProductPreview.as_view(), name='product_preview'),
    path('search', SearchList.as_view(), name='search'),
    path('search/page/<int:page>', SearchList.as_view(), name='search'),
]

products/models.py
import os

from django.utils.html import format_html

from extensions.utils import jalali_converter
from account.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

    def get_by_id(self, product_id):
        qs = self.get_queryset().filter(id=product_id)
        if qs.count() == 1:
            return qs.first()
        else:
            return None


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.publish}-{instance.title}{ext}"
    return f"products/{final_name}"


class ProductsManager(models.Manager):

    def get_by_id(self, product_id):
        qs = self.get_queryset().filter(id=product_id)
        if qs.count() == 1:
            return qs.first()
        else:
            return None


class Category(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان دسته‌بندی')
    slug = models.SlugField(verbose_name='آدرس دسته‌بندی', max_length=300, unique=True)
    image = models.ImageField(upload_to='category', null=True, verbose_name='عکس دسته بندی')
    status = models.BooleanField(default=True, verbose_name='آیا نمایش داده شود')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته‌بندی'
        verbose_name_plural = 'دسته‌بندی ها'

    def get_absolute_url(self):
        return reverse('account:category')


class Collection(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان کالکشن')
    slug = models.SlugField(verbose_name='شناسه کالکشن', max_length=300, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'کالکشن'
        verbose_name_plural = 'کالکشن ها'

    def get_absolute_url(self):
        return reverse('account:collection')


class Product(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش‌نویس'),
        ('p', 'انتشار')
    )
    title = models.CharField(max_length=300, verbose_name='عنوان محصول')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='نویسنده')
    parts = models.IntegerField(default=1, verbose_name='تعداد قطعات مونتاژ')
    slug = models.SlugField(verbose_name='آدرس محصول', null=True, max_length=200, unique=True)
    category = models.ManyToManyField(Category, verbose_name='دسته‌بندی', related_name='product')
    collection = models.ManyToManyField(Collection, verbose_name='کالکشن', related_name='product')
    description = models.TextField(verbose_name='توضیحات بیشتر', null=True, blank=True)
    color = models.CharField(max_length=300, verbose_name='رنگ', null=True, blank=True)
    technique = models.CharField(max_length=300, verbose_name='تکنیک', null=True, blank=True)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True, verbose_name='عکس محصول')
    image_1 = models.ImageField(upload_to=upload_image_path, null=True, blank=True, verbose_name='ادیت محصول')
    model_3dm = models.FileField(upload_to=upload_image_path, null=True, blank=True, verbose_name='فایل سه بعدی (3DM)')
    model_3dm_1 = models.FileField(upload_to=upload_image_path, null=True, blank=True,
                                   verbose_name='ادیت فایل سه بعدی (3DM)')
    model_stl = models.FileField(upload_to=upload_image_path, null=True, blank=True, verbose_name='فایل سه بعدی (STL)')
    model_stl_1 = models.FileField(upload_to=upload_image_path, null=True, blank=True,
                                   verbose_name='ادیت فایل سه بعدی (STL)')
    publish = models.DateTimeField(default=timezone.now, verbose_name='تاریخ انتشار')
    updated = models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, null=True, verbose_name='وضعیت')

    def __str__(self):
        return self.slug

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def get_absolute_url(self):
        return reverse('account:dashboard')

    def get_absolute(self):
        return f"/products/{self.id}/{self.title.replace(' ', '-')}"

    def category_to_str(self):
        return ",".join([category.title for category in self.category_published()])

    category_to_str.short_description = 'دسته‌بندی'

    def collection_to_str(self):
        return ",".join([collection.slug for collection in self.collection_all()])

    collection_to_str.short_description = 'کالکشن'

    def collection_all(self):
        return self.collection.all()

    def category_published(self):
        return self.category.filter(status=True)

    def j_publish(self):
        return jalali_converter(self.publish)

    j_publish.short_description = 'زمان انتشار'

    objects = ArticleManager()

products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from order.forms import UserOrderForm
from products.models import Product, Category, Collection
from account.mixins import AuthorAccessPreviewMixin
from django.contrib.auth.decorators import login_required


class ProductList(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'product/products-list.html'
    queryset = Product.objects.filter(status='p')
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # selected_product_id = kwargs['productId']
        context['category'] = Category.objects.filter(status=True)
        context['collection'] = Collection.objects.all()
        context['new-order'] = UserOrderForm(self.request.POST or None)
        return context


@login_required
def product_detail_view(request, slug, *args, **kwargs):
    selected_product_id = kwargs['productId']
    new_order_form = UserOrderForm(request.POST or None, initial={'product_id': selected_product_id})
    product = get_object_or_404(Product, slug=slug, status='p')
    category = Category.objects.filter(status=True)
    context = {
        'product': product,
        'category': category,
        'new_order': new_order_form,
    }
    return render(request, 'product/product-detail.html', context)


# def product_detail_preview(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     category = Category.objects.filter(status=True)
#     context = {
#         'product': product,
#         'category': category,
#     }
#     return render(request, 'product/product-detail.html', context)


class ProductPreview(AuthorAccessPreviewMixin, DetailView):
    template_name = 'product/product-detail.html'

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Product, pk=pk)


class SearchList(LoginRequiredMixin, ListView):
    template_name = 'product/search_list.html'
    paginate_by = 9

    def get_queryset(self):
        search = self.request.GET.get('q')
        return Product.objects.filter(
            Q(description__icontains=search) | Q(title__icontains=search) | Q(slug__icontains=search) | Q(
                color__icontains=search), status='p')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

products/templates/product/button_component.html
<form action="{% url 'order:new-order' %}" method="post">
    {% csrf_token %}
                                                <label>تعداد :</label>
    {{ new_order.product_id }}
    {{ new_order.count }}
    <button type="submit" class="btn btn-fefault cart">
        <i class="fa fa-shopping-cart"></i>
        افـزودن به سبـد خریـد
    </button>
</form>

products/templates/product/cat_component.html
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>دسته بندی ها</h2>
        <div class="panel-group category-products" id="accordian"><!--category-productsr-->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title"><a href="{% url 'product:product_list' %}">همه</a></h4>
                </div>
            </div>
            {% for cat in category %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a
                                href="{% url 'portal:category' cat.slug %}">{{ cat.title }}</a></h4>
                    </div>
                </div>
            {% endfor %}
        </div><!--/category-productsr-->
    </div>
</div>

<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>کالکشن ها</h2>
        <div class="panel-group category-products" id="accordian"><!--category-productsr-->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title"><a href="{% url 'product:product_list' %}">همه</a></h4>
                </div>
            </div>
            {% for col in collection %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a
                                href="{% url 'portal:collection' col.slug %}">{{ col.title }} ({{ col.slug }})</a></h4>
                    </div>
                </div>
            {% endfor %}
        </div><!--/category-productsr-->
    </div>
</div>

products/templates/product/category.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}محصولات | پورتال ای جی{% endblock %}
{% block content %}
    <section class="section site-portfolio">
        {% if user.is_authenticated %}
            <div class="row">
                <div class="container">
                    <div class="col-sm-9 padding-right">
                        <div class="features_items"><!--features_items-->
                            <h2 class="title text-center">محصولات</h2>
                            {% for item in object_list %}
                                {% include 'product/product_component.html' %}
                            {% endfor %}
                        </div><!--features_items-->
                        <div class="row">
                            <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">«</a></li>
                        {% endif %}
                        {% for page in paginator.page_range %}
                            <li class="{% if page == page_obj.number %}active{% endif %}"><a
                                    href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">»</a></li>
                        {% endif %}
                    </ul>
                        </div>
                    </div>
                    {% include 'product/cat_component.html' %}
                </div>
            </div>
        {% else %}
            <div class="col-lg-6 mx-auto">
                <div class="card card-danger">
                    <div class="card-header bg-danger ">
                        <h3 class="card-title text-light mb-0 float-left">EG STYLE</h3>
                    </div>
                    <div class="card-body">
                            <p>برای دیدن محتواهای سایت باید وارد شوید</p>
                        <a class="btn btn-outline-danger" href="{% url 'account:login' %}">ورود به سایت</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </section>
{% endblock %}

products/templates/product/collection.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}محصولات | پورتال ای جی{% endblock %}
{% block content %}
    <section class="section site-portfolio">
        {% if user.is_authenticated %}
            <div class="row">
                <div class="container">
                    <div class="col-sm-9 padding-right">
                        <div class="features_items"><!--features_items-->
                            <h2 class="title text-center">محصولات</h2>
                            {% for item in object_list %}
                                {% include 'product/product_component.html' %}
                            {% endfor %}
                        </div><!--features_items-->
                        <div class="row">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">«</a></li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    <li class="{% if page == page_obj.number %}active{% endif %}"><a
                                            href="?page={{ page }}">{{ page }}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}">»</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    {% include 'product/cat_component.html' %}

                </div>
            </div>
        {% else %}
            <div class="col-lg-6 mx-auto">
                <div class="card card-danger">
                    <div class="card-header bg-danger ">
                        <h3 class="card-title text-light mb-0 float-left">EG STYLE</h3>
                    </div>
                    <div class="card-body">
                        <p>برای دیدن محتواهای سایت باید وارد شوید</p>
                        <a class="btn btn-outline-danger" href="{% url 'account:login' %}">ورود به سایت</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </section>
{% endblock %}

products/templates/product/product-detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <section class="section site-portfolio">
        {% if user.is_authenticated %}
            <div class="row">
                <div class="container">
                    <div class="col-sm-9  padding-right">
                        <div class="product-details"><!--product-details-->
                            <div class="col-sm-5">
                                <div class="view-product">
                                    <img src="{{ product.image.url }}" alt="">
                                    <a href="{{ product.image.url }}"><h3>بزرگنمایـی</h3></a>
                                </div>
                            </div>
                            <div class="col-sm-7">
                                <div class="product-information"><!--/product-information-->
                                    <img src="{% static 'images/product-details/new.png' %}" class="newarrival" alt="">
                                    <div>
                                        <h2>{{ product.title }}</h2>
                                        <p>شناسـه : {{ product.title }}</p>
                                    </div>
                                    <div>
                                        <div>
                                            <p><b>تعداد قطعات : </b> {{ product.parts }}</p>
                                            <p><b>دسته بندی : </b> {{ product.category_to_str}}</p>
                                            <p><b>طراح : </b> {{ product.author.get_full_name }}</p>
                                            <p><b>رنگ : </b> {{ product.color }}</p>
                                            <p><b>تکنیک : </b> {{ product.technique }}</p>
                                        </div>
                                        <span>
                                            <form action="{% url 'order:new-order' %}" method="post">
                                                {% csrf_token %}
                                                {{ new_order.product_id }}
                                                {{ new_order.count }}
                                                <button type="submit" class="btn btn-fefault cart">
                                                    <i class="fa fa-shopping-cart"></i>
                                                    افـزودن به سبـد خریـد
                                                </button>
                                            </form>
                                        </span>
                                    </div>
                                </div><!--/product-information-->
                            </div>
                        </div><!--/product-details-->
                    </div>
                    {% include 'product/cat_component.html' %}
                </div>
            </div>
        {% else %}
            <div class="col-lg-6 mx-auto">
                <div class="card card-danger">
                    <div class="card-header bg-danger ">
                        <h3 class="card-title text-light mb-0 float-left">EG STYLE</h3>
                    </div>
                    <div class="card-body">
                        <p>برای دیدن محتواهای سایت باید وارد شوید</p>
                        <a class="btn btn-outline-danger" href="{% url 'account:login' %}">ورود به سایت</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </section>
{% endblock %}

products/templates/product/product_component.html
{% load thumbnail %}
<div class="col-sm-4 pull-right">
    <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center">
                {% thumbnail item.image "250x140" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}"
                         height="{{ im.height }}">
                {% endthumbnail %}
                <a href="{% url 'product:product_detail' item.id item.slug %}">
                        <h2>{{ item.title }}</h2></a>
                <p>{{ item.description|truncatewords:5|safe }}</p>
            </div>
        </div>
        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href="{% url 'product:product_detail' item.id item.slug %}"><i class="fa fa-plus-square"></i>نمایش
                    محصول</a>
                </li>
            </ul>
        </div>
    </div>
</div>

products/templates/product/products-list.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}محصولات | پورتال ای جی{% endblock %}
{% block content %}
    <section class="section site-portfolio">
        {% if user.is_authenticated %}
            <div class="row">
                <div class="container">
                    <div class="col-sm-9 padding-right">
                        <div class="features_items"><!--features_items-->
                            <h2 class="title text-center">محصولات</h2>
                            {% for item in object_list %}
                                {% include 'product/product_component.html' %}
                            {% endfor %}
                        </div><!--features_items-->
                        <div class="row">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">«</a></li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    <li class="{% if page == page_obj.number %}active{% endif %}"><a
                                            href="?page={{ page }}">{{ page }}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}">»</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    {% include 'product/cat_component.html' %}

                </div>
            </div>
        {% else %}
            <div class="col-lg-6 mx-auto">
                <div class="card card-danger">
                    <div class="card-header bg-danger ">
                        <h3 class="card-title text-light mb-0 float-left">EG STYLE</h3>
                    </div>
                    <div class="card-body">
                        <p>برای دیدن محتواهای سایت باید وارد شوید</p>
                        <a class="btn btn-outline-danger" href="{% url 'account:login' %}">ورود به سایت</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </section>
{% endblock %}

products/templates/product/search_list.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}محصولات | پورتال ای جی{% endblock %}
{% block content %}
    <section class="section site-portfolio">
        {% if user.is_authenticated %}
            <div class="row">
                <div class="container">
                    <div class="col-sm-9 padding-right">
                        <div class="features_items"><!--features_items-->
                            <h2 class="title text-center">محصولات</h2>
                            {% for item in object_list %}
                                {% include 'product/product_component.html' %}
                            {% endfor %}
                        </div><!--features_items-->
                        <div class="row">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li>
                                        <a href="{% url 'product:search' page_obj.previous_page_number %}?q={{ search }}">«</a>
                                    </li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    <li class="{% if page == page_obj.number %}active{% endif %}"><a
                                            href="{% url 'product:search' page %}?q={{ search }}">{{ page }}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li>
                                        <a href="{% url 'product:search' page_obj.next_page_number %}?q={{ search }}">»</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    {% include 'product/cat_component.html' %}
                </div>
            </div>
        {% else %}
            <div class="col-lg-6 mx-auto">
                <div class="card card-danger">
                    <div class="card-header bg-danger ">
                        <h3 class="card-title text-light mb-0 float-left">EG STYLE</h3>
                    </div>
                    <div class="card-body">
                        <p>برای دیدن محتواهای سایت باید وارد شوید</p>
                        <a class="btn btn-outline-danger" href="{% url 'account:login' %}">ورود به سایت</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </section>
{% endblock %}